#!/usr/bin/env python3

import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPORTS = os.path.join(ROOT, "synthesis", "reports")

SHARED_RTL = [
    "rtl/core/alu.sv", "rtl/core/regfile.sv", "rtl/core/imm_gen.sv",
    "rtl/core/decoder.sv",
    "rtl/mem/imem.sv", "rtl/mem/dmem.sv",
    "rtl/periph/uart_tx.sv", "rtl/periph/uart_rx.sv", "rtl/periph/uart.sv",
    "rtl/periph/timer.sv", "rtl/custom/dotp.sv",
]

TOPS = {
    "core_single": ["rtl/core/core_single.sv"],
    "core_multi":  ["rtl/core/core_multi.sv"],
    "core_pipe":   ["rtl/core/core_pipe.sv"],
    "dotp":        [],
    "uart":        [],
    "timer":       [],
    "imem":        [],
    "dmem":        [],
    "soc_single":  ["rtl/core/core_single.sv", "rtl/soc/soc_single.sv"],
    "soc_multi":   ["rtl/core/core_multi.sv",  "rtl/soc/soc_multi.sv"],
    "soc_pipe":    ["rtl/core/core_pipe.sv",   "rtl/soc/soc_pipe.sv"],
}

EXTRA = {k: v for k, v in TOPS.items()}

BLACKBOX = {"soc_single": ["imem", "dmem"],
            "soc_multi":  ["imem", "dmem"],
            "soc_pipe":   ["imem", "dmem"]}


def run_yosys(top, script, logpath):
    with open(logpath, "w") as f:
        r = subprocess.run(["yosys", "-s", "/dev/stdin"], cwd=ROOT, input=script,
                           capture_output=True, text=True, timeout=1800)
        f.write(r.stdout)
        f.write(r.stderr)
    return r.returncode == 0, r.stdout + r.stderr


def parse_stat(log):
    cells = {}
    in_stat = False
    for line in log.splitlines():
        if "Printing statistics" in line:
            in_stat = True
            continue
        if in_stat:
            m = re.match(r"^\s+([A-Za-z$_][A-Za-z0-9_$]*)\s+(\d+)\s*$", line)
            if m and m.group(1) not in ("Number", "Estimated"):
                cells[m.group(1)] = cells.get(m.group(1), 0) + int(m.group(2))
    luts = sum(v for k, v in cells.items() if re.fullmatch(r"LUT[0-9]", k) or k in ("LUT6_2",))
    ffs = sum(v for k, v in cells.items() if re.fullmatch(r"FD[A-Z]*", k))
    carries = sum(v for k, v in cells.items() if "CARRY" in k or k == "MUXCY")
    rams = sum(v for k, v in cells.items() if k.startswith("RAM"))
    mults = sum(v for k, v in cells.items() if "MULT" in k or "DSP" in k)
    total = sum(cells.values())
    return dict(luts=luts, ffs=ffs, carries=carries, rams=rams, mults=mults,
                total_cells=total, raw=cells)


def parse_ltp(log, top):
    m = re.search(r"Longest topological path in " + re.escape(top) + r"[^\n]*?length=(\d+)", log)
    if m:
        return int(m.group(1))
    m = re.search(r"longest topological path[^\n]*?length=(\d+)", log, re.I)
    return int(m.group(1)) if m else None


def read_files(top):
    return SHARED_RTL + EXTRA[top]


def blackbox_cmd(top):
    mods = BLACKBOX.get(top, [])
    return ("blackbox " + " ".join(mods) + "\n") if mods else ""


def main():
    os.makedirs(REPORTS, exist_ok=True)
    summary = {}

    for top, extra in TOPS.items():
        files = " ".join(read_files(top))
        print(f"[synth] {top} (xc7 mapping) ...")
        blackbox = blackbox_cmd(top)
        script = f"""# auto-generated by tools/run_synth.py
read_verilog -sv -DSYNTHESIS -I rtl/core {files}
{blackbox}hierarchy -check -top {top}
flatten
synth_xilinx -family xc7 -top {top}
stat
read_verilog -sv -DSYNTHESIS -I rtl/core {files}
{blackbox}hierarchy -check -top {top}
flatten
synth -top {top}
ltp -noff
